### ISSUE TITLE
Publish an how to.

### ISSUE THREAD

**Issue by meanpenguin** [jabelone/OpenCV-for-Pi#1]
Hi.  

Would you mind publishing an how to for makting the package?
I'm in need of making the opencv-contribs library as well.

**Comment by jabelone** [comment]
I'll try to get around to doing it this week. I'll also add opencv 3.2 now that it's out.

**Comment by razekmaiden** [comment]
Hi. My name is Jose Luis

I tried to create a package of dependencies to "install" your OpenCV version offline. The problem is that, after install the dependencies and the OpenCV, when I tried to  compile C++ code including OpenCV, I have errors due probably to that this "Installation" of OpenCV require specifics versions of each one of the dependencies (e.g. livavcodecs-dev 56, libavformat-dev 56, etc), but in synaptic I found only the lastest version (and the previous version are e.g. livavcodecs-dev 53 and livavcodecs-dev 54 but not the required). Do you have the *.deb files for que required dependencies? Do you can upload them?

**Comment by jabelone** [comment]
@razekmaiden please open a new issue as this has nothing to do with the original one.  @meanpenguin sorry I completely forgot about this, I've set a reminder so hopefully I'll get it done this week :)
